name: "42Crunch REST API Dynamic Security Testing"

on: push
jobs:
  Run-Scan:
    runs-on: ubuntu-latest
    steps:
    - id: Scan
      run: | 
        response=$(curl -k -d "user=userscan-run@acme.com&pass=hellopixi" -X POST https://api-protect.42crunch.cloud/turkishairlines/api/user/login | jq -r '.token')
        echo "response from curl= $response"
        
        docker pull 42crunch/scand-agent:v2.0.0
        docker run -e SCAN_TOKEN=scan_133a93fb-88ad-4f5e-be04-5881db65a5c6 -e SCAN42C_SECURITY_ACCESS_TOKEN=$response -e PLATFORM_SERVICE=services.42crunch.com:8001 -e SCAN42C_user=userscan-run@acme.com -e SCAN42C_pass=hellopixi 42crunch/scand-agent:v2.0.0